name: eztalk
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.2.0
  flutter_tts: ^4.0.2
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.3.2
  axios_package: ^0.0.3
  record: ^5.2.0
  flutter_sound: ^9.17.8
  path_provider: ^2.1.5
  just_audio: ^0.9.42
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
